CREATE TABLE  "ITENS" 
   (	
    "ID" NUMBER NOT NULL ENABLE, 
	"VENDA_ID" NUMBER NOT NULL ENABLE, 
	"PRODUTO_ID" NUMBER NOT NULL ENABLE, 
	"QTD" NUMBER NOT NULL ENABLE, 
	"VLR_UNITARIO" NUMBER NOT NULL ENABLE, 
	"TOTAL_ITEM" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "ITENS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "ITENS" ADD CONSTRAINT "ITENS_FK" FOREIGN KEY ("VENDA_ID")
	  REFERENCES  "VENDA" ("ID") ENABLE
/

CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_ITENS" 
  before insert on "ITENS"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "ITENS_SEQ".nextval into :NEW."ID" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_ITENS" ENABLE
/
